# Poco lib: use POCO_ROOT if set, else download prebuilt from GitHub Releases.
# Set POCO_LIB_VERSION (default 1.14.2), POCO_LIB_REPO (default paulocoutinhox/poco-lib),
# POCO_LIB_USE_PREBUILT (default ON) before including.

if(NOT DEFINED POCO_LIB_USE_PREBUILT)
  set(POCO_LIB_USE_PREBUILT ON)
endif()
if(DEFINED POCO_ROOT AND EXISTS "${POCO_ROOT}/include/Poco" AND EXISTS "${POCO_ROOT}/lib")
  set(_poco_prefix "${POCO_ROOT}")
elseif(POCO_LIB_USE_PREBUILT)
  if(NOT DEFINED POCO_LIB_VERSION)
    set(POCO_LIB_VERSION "1.14.2")
  endif()
  if(NOT DEFINED POCO_LIB_REPO)
    set(POCO_LIB_REPO "paulocoutinhox/poco-lib")
  endif()
  set(_poco_archive "")
  if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
    set(_poco_archive "poco-ios")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "tvOS")
    set(_poco_archive "poco-tvos")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "watchOS")
    set(_poco_archive "poco-watchos")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(_poco_archive "poco-android")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_poco_archive "poco-macos")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
      set(_poco_archive "poco-linux-aarch64")
    else()
      set(_poco_archive "poco-linux-x86_64")
    endif()
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
      set(_poco_archive "poco-windows-arm64")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
      set(_poco_archive "poco-windows-x64")
    else()
      set(_poco_archive "poco-windows-x86")
    endif()
  endif()
  if(_poco_archive STREQUAL "")
    message(FATAL_ERROR "poco-lib: unsupported platform ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}")
  endif()
  set(_poco_url "https://github.com/${POCO_LIB_REPO}/releases/download/v${POCO_LIB_VERSION}/${_poco_archive}.zip")
  set(_poco_dl "${CMAKE_BINARY_DIR}/_deps/poco-lib/${_poco_archive}.zip")
  set(_poco_extract "${CMAKE_BINARY_DIR}/_deps/poco-lib/src")
  file(DOWNLOAD "${_poco_url}" "${_poco_dl}" TLS_VERIFY ON STATUS _poco_status)
  list(GET _poco_status 0 _poco_code)
  if(NOT _poco_code EQUAL 0)
    message(FATAL_ERROR "poco-lib: download failed (${_poco_code}) for ${_poco_url}")
  endif()
  file(ARCHIVE_EXTRACT INPUT "${_poco_dl}" DESTINATION "${_poco_extract}")
  if(EXISTS "${_poco_extract}/include/Poco" AND EXISTS "${_poco_extract}/lib")
    set(_poco_prefix "${_poco_extract}")
  elseif(EXISTS "${_poco_extract}/${_poco_archive}/include/Poco" AND EXISTS "${_poco_extract}/${_poco_archive}/lib")
    set(_poco_prefix "${_poco_extract}/${_poco_archive}")
  else()
    file(GLOB _poco_top "${_poco_extract}/*")
    list(LENGTH _poco_top _poco_len)
    if(_poco_len EQUAL 1)
      list(GET _poco_top 0 _poco_one)
      if(IS_DIRECTORY "${_poco_one}" AND EXISTS "${_poco_one}/include/Poco" AND EXISTS "${_poco_one}/lib")
        set(_poco_prefix "${_poco_one}")
      else()
        set(_poco_prefix "${_poco_extract}")
      endif()
    else()
      set(_poco_prefix "${_poco_extract}")
    endif()
  endif()
  if(NOT EXISTS "${_poco_prefix}/include/Poco" OR NOT EXISTS "${_poco_prefix}/lib")
    message(FATAL_ERROR "poco-lib: extracted layout unexpected at ${_poco_prefix}")
  endif()
else()
  message(FATAL_ERROR "poco-lib: POCO_ROOT not set and POCO_LIB_USE_PREBUILT is OFF")
endif()

set(POCO_ROOT "${_poco_prefix}" CACHE PATH "Poco lib root" FORCE)

# Prefer lib/Release on Windows when present
set(_poco_lib_dir "${POCO_ROOT}/lib")
if(MSVC AND IS_DIRECTORY "${POCO_ROOT}/lib/Release")
  set(_poco_lib_dir "${POCO_ROOT}/lib/Release")
endif()

# Transitive deps (bundled in archive): OpenSSL, zlib, pcre2, utf8proc, expat (XML)
if(NOT TARGET "POCO::Deps")
  add_library("POCO::Deps" INTERFACE IMPORTED GLOBAL)
  set_target_properties("POCO::Deps" PROPERTIES
    INTERFACE_LINK_DIRECTORIES "${_poco_lib_dir}")
  if(MSVC)
    set_target_properties("POCO::Deps" PROPERTIES
      INTERFACE_LINK_LIBRARIES "libssl" "libcrypto" "zlib" "pcre2-8" "pcre2-posix" "utf8proc" "libexpat")
  else()
    set_target_properties("POCO::Deps" PROPERTIES
      INTERFACE_LINK_LIBRARIES "ssl" "crypto" "z" "pcre2-8" "pcre2-posix" "utf8proc" "expat")
  endif()
endif()

set(_poco_components PocoFoundation PocoNet PocoUtil PocoXML PocoZip PocoCrypto PocoNetSSL)
foreach(_comp IN LISTS _poco_components)
  if(NOT TARGET "${_comp}")
    add_library("${_comp}" INTERFACE IMPORTED GLOBAL)
    set_target_properties("${_comp}" PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${POCO_ROOT}/include"
      INTERFACE_LINK_DIRECTORIES "${_poco_lib_dir}"
      INTERFACE_LINK_LIBRARIES "${_comp}")
    target_link_libraries("${_comp}" INTERFACE "POCO::Deps")
  endif()
endforeach()
