name: Build Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Build
        run: python scripts/build.py windows

      - uses: actions/upload-artifact@v4
        with:
          name: poco-windows-x64
          path: output/windows-x64/

      - uses: actions/upload-artifact@v4
        with:
          name: poco-windows-x86
          path: output/windows-x86/

      - uses: actions/upload-artifact@v4
        with:
          name: poco-windows-arm64
          path: output/windows-arm64/