name: Build tvOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        run: |
          python3 -m venv .venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Build
        run: python scripts/build.py tvos

      - uses: actions/upload-artifact@v4
        with:
          name: poco-tvos
          path: output/tvos/
